---
site:
  title: 'LB2865 Container Hardening: Zero to Hero'
  start_page: modules::index.adoc

content:
  sources:
  - url: .
    start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/v2.0.2/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ./content/supplemental-ui
  - path: ./content/lib

antora:
  extensions:
  - '@sntke/antora-mermaid-extension'
  - require: ./content/lib/inject-buttons.js

output:
  dir: ./www
